services:
  ai:
    image: ollama/ollama
    container_name: ai
    hostname: ai
    networks:
      - ai-playground
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    hostname: open-webui
    networks:
      - ai-playground
    ports:
      - "3000:8080"
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URL: "http://ai:11434"
      WEBUI_AUTH: false
networks:
  ai-playground:
    name: ai-playground